### ISSUE TITLE
When translating the word

### ISSUE THREAD

**Issue by RezaSh13** [SiminDictionary/simin#1]
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps.conf", line 8: unknown element "description"
Traceback (most recent call last):
  File "main.py", line 36, in <lambda>
    self.pushButton.clicked.connect(lambda:self.trnsl(None))
  File "main.py", line 122, in trnsl
    gtrans = Gtranslate().translate(sl, tl, word)
  File "/opt/simin/GT.py", line 34, in translate
    dbc.insertWord(word, exactmean, othmean, pron)
  File "/opt/simin/DB.py", line 30, in insertWord
    if self.conn.execute("INSERT INTO dict(word, mean, othmean, pron) VALUES(?, ?, ?, ?)", (str(word).strip(), str(mean), str(othmean), str(pron))):
sqlite3.OperationalError: attempt to write a readonly database
/usr/bin/simin: line 2:  1477 Aborted                 (core dumped) python3 main.py

**Comment by Moork0** [comment]
what is your /opt/simin directory permissions ? did you try to uninstall and reinstalling the app ?

**Comment by HrBDev** [comment]
I have the same problem.
My permission for /opt/simin is drwxr-xr-x(755)

**Comment by Moork0** [comment]
Well ... then you should not have any problem like this.
Please send this commands result : 
ls -l /opt/simin/dbs/
id
Thanks.

**Comment by HrBDev** [comment]
Changing the owner from root to my own user fixed it.

**Comment by Moork0** [comment]
This have to be done automatically in _install.sh_ already ...
